insert into public.article_tags (name, slug)
values ('Python', 'python'),
       ('Django', 'django'),
       ('Algorithms', 'algorithms'),
       ('Data Structures', 'data-structures'),
       ('REST API', 'rest-api'),
       ('Design Patterns', 'design-patterns'),
       ('Code Optimization', 'code-optimization'),
       ('HTML', 'html'),
       ('CSS', 'css'),
       ('JavaScript', 'javascript'),
       ('React', 'react'),
       ('Vue.js', 'vue.js'),
       ('Tailwind CSS', 'tailwind-css'),
       ('Responsive Design', 'responsive-design'),
       ('Machine Learning', 'machine-learning'),
       ('Data Visualization', 'data-visualization'),
       ('Pandas', 'pandas'),
       ('NumPy', 'numpy'),
       ('Scikit-Learn', 'scikit-learn'),
       ('Matplotlib', 'matplotlib'),
       ('CI/CD', 'ci-cd'),
       ('Docker', 'docker'),
       ('Kubernetes', 'kubernetes'),
       ('Ansible', 'ansible'),
       ('Terraform', 'terraform'),
       ('Cloud', 'cloud'),
       ('Jenkins', 'jenkins'),
       ('Networking', 'networking'),
       ('Firewalls', 'firewalls'),
       ('VPN', 'vpn'),
       ('Security', 'security'),
       ('Linux', 'linux'),
       ('Windows Server', 'windows-server'),
       ('Troubleshooting', 'troubleshooting'),
       ('IT Support', 'it-support'),
       ('Helpdesk', 'helpdesk'),
       ('SysAdmin', 'sysadmin'),
       ('Scripting', 'scripting'),
       ('Bouldering', 'bouldering'),
       ('Sport Climbing', 'sport-climbing'),
       ('Trad Climbing', 'trad-climbing'),
       ('Training', 'training'),
       ('Gear Reviews', 'gear-reviews'),
       ('Marathon', 'marathon'),
       ('5K', '5k'),
       ('10K', '10k'),
       ('Training Plans', 'training-plans'),
       ('Gear', 'gear'),
       ('Trail Running', 'trail-running'),
       ('Strength Training', 'strength-training'),
       ('Flexibility', 'flexibility'),
       ('Cardio', 'cardio'),
       ('HIIT', 'hiit'),
       ('Yoga', 'yoga');

insert into public.article_topics (name, slug, description)
values ('Software Development',
        'software-development',
        'Articles about programming concepts, software design patterns, tutorials, and code samples.'),
       ('Web Development',
        'web-development',
        'Focused on frontend and backend web development, covering topics like HTML, CSS, JavaScript, Django, and APIs.'),
       ('Data Science & Analytics',
        'data-science-analytics',
        'Data analysis, machine learning, and insights on handling and visualizing data with Python or other tools.'),
       ('DevOps & Automation',
        'devops-automation',
        'Content on CI/CD, Docker, Kubernetes, server automation, and configuration management.'),
       ('IT Infrastructure',
        'it-infrastructure',
        'Topics on networking, servers, security, and infrastructure management.'),
       ('IT Operations & Support',
        'it-operations-support',
        'Day-to-day IT operations, troubleshooting, and support tips for both on-premises and cloud systems.'),
       ('Climbing',
        'climbing',
        'Personal experiences, climbing techniques, training tips, and gear recommendations for bouldering and climbing.'),
       ('Running',
        'running',
        'Articles covering running routines, training plans, race experiences, and gear reviews.'),
       ('Fitness',
        'fitness',
        'General fitness tips, strength training routines, flexibility exercises, and maintaining overall health.');
