// Reads migration/articles.json and writes supabase/seeds/08_migrated_articles.sql
// Run: node migration/generate-seed.mjs
import { readFileSync, writeFileSync } from 'fs'
import { randomUUID } from 'crypto'
import TurndownService from 'turndown'

const AUTHOR_UUID = '3a455a9e-9a96-4fa1-aef9-8591690084e6'
const INPUT_FILE = 'migration/articles.json'
const OUTPUT_FILE = 'supabase/seeds/08_migrated_articles.sql'

const turndown = new TurndownService({
  headingStyle: 'atx',
  codeBlockStyle: 'fenced',
  bulletListMarker: '-',
})

// Replace LaTeX delimiters with placeholders BEFORE Turndown runs.
// Turndown doubles backslashes (\[ → \\[), which would break the regex.
// Placeholders are plain alphanumeric so Turndown leaves them untouched.
function extractLatex(html) {
  const placeholders = []

  let result = html.replace(/\\\[([\s\S]*?)\\\]/g, (_, inner) => {
    const index = placeholders.length
    placeholders.push(`\n$$${inner.trim()}$$\n`)
    return `DISPLAYLATEX${index}PLACEHOLDER`
  })

  result = result.replace(/\\\(([\s\S]*?)\\\)/g, (_, inner) => {
    const index = placeholders.length
    placeholders.push(`$${inner.trim()}$`)
    return `INLINELATEX${index}PLACEHOLDER`
  })

  return { result, placeholders }
}

function restoreLatex(markdown, placeholders) {
  let result = markdown
  for (let index = 0; index < placeholders.length; index++) {
    const value = placeholders[index]
    // Use a function as the replacement to prevent $ being treated as a special
    // replacement pattern — string.replace(str, '$$x$$') reduces '$$' to '$'.
    result = result
      .replace(`DISPLAYLATEX${index}PLACEHOLDER`, () => value)
      .replace(`INLINELATEX${index}PLACEHOLDER`, () => value)
  }
  return result
}

// Some articles are stored with entity-encoded HTML inside an outer <p> wrapper
// (a Django/CKEditor artifact). Detect and unwrap before Turndown runs, otherwise
// Turndown outputs the entity-decoded angle brackets as literal text characters.
function unwrapDoubleEncoded(html) {
  const trimmed = html.trim()
  if (/^<p[^>]*>&lt;/.test(trimmed)) {
    const inner = trimmed.replace(/^<p[^>]*>/, '').replace(/<\/p>\s*$/, '')
    return inner
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&apos;/g, "'")
      .replace(/&rsquo;/g, '’')
      .replace(/&lsquo;/g, '‘')
      .replace(/&ldquo;/g, '“')
      .replace(/&rdquo;/g, '”')
      .replace(/&mdash;/g, '—')
      .replace(/&ndash;/g, '–')
      .replace(/&hellip;/g, '…')
      .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
      .replace(/&amp;/g, '&')
  }
  return html
}

function convertContent(html) {
  const normalized = unwrapDoubleEncoded(html)
  const { result: preprocessed, placeholders } = extractLatex(normalized)
  let markdown = turndown.turndown(preprocessed)
  markdown = restoreLatex(markdown, placeholders)
  markdown = markdown.replace(/\r\n/g, '\n').replace(/\r/g, '\n')
  markdown = markdown.replace(/ /g, ' ')
  return markdown
}

function q(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

function dollarQuote(content) {
  if (content.includes('$article$')) {
    throw new Error(`Article content contains the dollar-quote tag "$article$" — use a different tag for this article.`)
  }
  return `$article$${content}$article$`
}

function main() {
  const articles = JSON.parse(readFileSync(INPUT_FILE, 'utf-8'))

  const categories = new Map()
  const tags = new Map()
  const seriesMap = new Map()

  for (const article of articles) {
    if (article.category) categories.set(article.category.slug, article.category)
    for (const tag of article.tags) tags.set(tag.slug, tag)
    if (article.series && !seriesMap.has(article.series.slug)) {
      seriesMap.set(article.series.slug, { ...article.series, uuid: randomUUID() })
    }
  }

  const lines = []
  lines.push('-- Migrated articles from schirDev Django site')
  lines.push('-- Generated by migration/generate-seed.mjs — do not edit by hand')
  lines.push('')

  // Categories
  if (categories.size > 0) {
    lines.push('-- Categories')
    for (const cat of categories.values()) {
      lines.push(`insert into public.article_categories (name, slug, description)`)
      lines.push(`values (${q(cat.name)}, ${q(cat.slug)}, ${q(cat.description ?? '')})`)
      lines.push(`on conflict (slug) do nothing;`)
      lines.push('')
    }
  }

  // Tags
  if (tags.size > 0) {
    lines.push('-- Tags')
    const tagRows = [...tags.values()].map(tag => `    (${q(tag.name)}, ${q(tag.slug)})`)
    lines.push(`insert into public.article_tags (name, slug)`)
    lines.push(`values`)
    lines.push(tagRows.join(',\n'))
    lines.push(`on conflict (slug) do nothing;`)
    lines.push('')
  }

  // Series
  if (seriesMap.size > 0) {
    lines.push('-- Article series')
    for (const series of seriesMap.values()) {
      lines.push(`insert into public.article_series (id, title, slug, description, author)`)
      lines.push(`values (${q(series.uuid)}, ${q(series.title)}, ${q(series.slug)}, ${q(series.description ?? '')}, '${AUTHOR_UUID}')`)
      lines.push(`on conflict (slug) do nothing;`)
      lines.push('')
    }
  }

  // Articles
  const articleUuids = new Map()
  lines.push('-- Articles')

  for (const article of articles) {
    const uuid = randomUUID()
    articleUuids.set(article.slug, uuid)

    const content = convertContent(article.content)
    const categoryRef = article.category
      ? `(select id from public.article_categories where slug = ${q(article.category.slug)})`
      : 'null'
    const seriesId = article.series ? q(seriesMap.get(article.series.slug).uuid) : 'null'
    const seriesSeq = article.series?.sequence_number ?? 'null'
    const writingStage = article.is_published ? 'ready' : 'draft'
    const publishedAt = article.is_published ? q(article.created_at) : 'null'

    lines.push(`-- ${article.title}`)
    lines.push(`insert into public.articles`)
    lines.push(`    (id, title, slug, content, category_id, series_id, series_sequence_number,`)
    lines.push(`     author, writing_stage, published_at, view_count, created_at, updated_at)`)
    lines.push(`values (`)
    lines.push(`    ${q(uuid)}, ${q(article.title)}, ${q(article.slug)},`)
    lines.push(`    ${dollarQuote(content)},`)
    lines.push(`    ${categoryRef},`)
    lines.push(`    ${seriesId}, ${seriesSeq},`)
    lines.push(`    '${AUTHOR_UUID}', '${writingStage}', ${publishedAt},`)
    lines.push(`    ${article.view_count ?? 0},`)
    lines.push(`    ${q(article.created_at)}, ${q(article.created_at)}`)
    lines.push(`)`)
    lines.push(`on conflict (slug) do nothing;`)
    lines.push('')
  }

  // Tag links
  const articlesWithTags = articles.filter(article => article.tags.length > 0)
  if (articlesWithTags.length > 0) {
    lines.push('-- Tag links')
    for (const article of articlesWithTags) {
      const uuid = articleUuids.get(article.slug)
      const slugList = article.tags.map(tag => q(tag.slug)).join(', ')
      lines.push(`insert into public.article_tags_links (article_id, tag_id)`)
      lines.push(`select ${q(uuid)}, id from public.article_tags where slug in (${slugList})`)
      lines.push(`on conflict do nothing;`)
      lines.push('')
    }
  }

  writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8')

  console.log(`✓ Written to ${OUTPUT_FILE}`)
  console.log(`  Articles:   ${articles.length}`)
  console.log(`  Categories: ${categories.size} (new or merged with existing)`)
  console.log(`  Tags:       ${tags.size} (new or merged with existing)`)
  console.log(`  Series:     ${seriesMap.size}`)
}

main()
