insert into public.article_tags (name, slug, icon)
values ('Python', 'python', 'logos:python'),
       ('Django', 'django', 'logos:django-icon'),
       ('Algorithms', 'algorithms', null),
       ('Data Structures', 'data-structures', null),
       ('REST API', 'rest-api', null),
       ('Design Patterns', 'design-patterns', null),
       ('Code Optimization', 'code-optimization', null),
       ('HTML', 'html', 'logos:html-5'),
       ('CSS', 'css', 'logos:css-3'),
       ('JavaScript', 'javascript', 'logos:javascript'),
       ('React', 'react', 'logos:react'),
       ('Vue.js', 'vue.js', 'logos:vue'),
       ('Tailwind CSS', 'tailwind-css', 'logos:tailwindcss-icon'),
       ('Responsive Design', 'responsive-design', null),
       ('Machine Learning', 'machine-learning', null),
       ('Data Visualization', 'data-visualization', null),
       ('Pandas', 'pandas', 'logos:pandas-icon'),
       ('NumPy', 'numpy', null),
       ('Scikit-Learn', 'scikit-learn', null),
       ('Matplotlib', 'matplotlib', null),
       ('CI/CD', 'ci-cd', null),
       ('Docker', 'docker', 'logos:docker-icon'),
       ('Kubernetes', 'kubernetes', 'logos:kubernetes'),
       ('Ansible', 'ansible', 'logos:ansible'),
       ('Terraform', 'terraform', 'logos:terraform-icon'),
       ('Cloud', 'cloud', null),
       ('Jenkins', 'jenkins', 'logos:jenkins'),
       ('Networking', 'networking', null),
       ('Firewalls', 'firewalls', null),
       ('VPN', 'vpn', null),
       ('Security', 'security', null),
       ('Linux', 'linux', 'logos:linux-tux'),
       ('Windows Server', 'windows-server', 'logos:microsoft-windows-icon'),
       ('Troubleshooting', 'troubleshooting', null),
       ('IT Support', 'it-support', null),
       ('Helpdesk', 'helpdesk', null),
       ('SysAdmin', 'sysadmin', null),
       ('Scripting', 'scripting', null),
       ('Bouldering', 'bouldering', null),
       ('Sport Climbing', 'sport-climbing', null),
       ('Trad Climbing', 'trad-climbing', null),
       ('Training', 'training', null),
       ('Gear Reviews', 'gear-reviews', null),
       ('Marathon', 'marathon', null),
       ('5K', '5k', null),
       ('10K', '10k', null),
       ('Training Plans', 'training-plans', null),
       ('Gear', 'gear', null),
       ('Trail Running', 'trail-running', null),
       ('Strength Training', 'strength-training', null),
       ('Flexibility', 'flexibility', null),
       ('Cardio', 'cardio', null),
       ('HIIT', 'hiit', null),
       ('Yoga', 'yoga', null);

insert into public.article_categories (name, slug, description, color)
values ('Software Development',
        'software-development',
        'Articles about programming concepts, software design patterns, tutorials, and code samples.',
        '#7c3aed'),
       ('Web Development',
        'web-development',
        'Focused on frontend and backend web development, covering topics like HTML, CSS, JavaScript, Django, and APIs.',
        '#4f46e5'),
       ('Data Science & Analytics',
        'data-science-analytics',
        'Data analysis, machine learning, and insights on handling and visualizing data with Python or other tools.',
        '#0284c7'),
       ('DevOps & Automation',
        'devops-automation',
        'Content on CI/CD, Docker, Kubernetes, server automation, and configuration management.',
        '#0891b2'),
       ('IT Infrastructure',
        'it-infrastructure',
        'Topics on networking, servers, security, and infrastructure management.',
        '#475569'),
       ('IT Operations & Support',
        'it-operations-support',
        'Day-to-day IT operations, troubleshooting, and support tips for both on-premises and cloud systems.',
        '#64748b'),
       ('Climbing',
        'climbing',
        'Personal experiences, climbing techniques, training tips, and gear recommendations for bouldering and climbing.',
        '#16a34a'),
       ('Running',
        'running',
        'Articles covering running routines, training plans, race experiences, and gear reviews.',
        '#dc2626'),
       ('Fitness',
        'fitness',
        'General fitness tips, strength training routines, flexibility exercises, and maintaining overall health.',
        '#ea580c');